theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/singularitti/BisectPy.jl/archive/refs/tags/v1.0.0.zip
  tar_url: https://github.com/singularitti/BisectPy.jl/archive/refs/tags/v1.0.0.tar.gz
